env:
  browser: true
  es2021: true
  jquery: true
extends: 'eslint:recommended'
globals:
  L: true
  LastFM: true
  LastFMCache: true
  Modernizr: true
parserOptions:
  ecmaVersion: 12
plugins:
  - only-warn
rules:
  no-unused-vars:
    - warn
    - args: none
